name: Tabify

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Repo checkout
      uses: actions/checkout@v2
    - name: Tabify
      uses: ayan-b/tabifier-action@master
      env:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      with:
        tabLength: 4
    - name: Commit and push
      run: |
        git status
        git add .
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git commit -m "Tabify"
        git push https://ayan-b:${GITHUB_TOKEN}@github.com/ayan-b/tabify-playground HEAD:master
